name: fl-nids
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  # 1. The Core Infrastructure 
  - python=3.10          
  - pytorch        
  - pytorch-cuda=11.8    
  - numpy<2.2
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - tqdm             # Progress bars
  - numba
  - llvmlite
  - pynndescent
  - umap-learn
  - pip                  

  # 2. The Python Libraries (Installed via pip inside conda)
  - pip:
      
      - wandb            # For Weights & Biases logging
      - hydra-core       # For Config management
      
# to run this 
# conda env create -f environment.yml
# to activate this
# conda activate fl-nids